name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test --verbose
    - name: upload_binary
      uses: actions/upload-artifact@v4
      with:
        name: panel-activity_log-cleaner
        path: target/release/panel-activity_log-cleaner
